Update training-setup.sh
there was an error in the script with the latest version.  I added a pip gym install version so it would work.  TODO: fix for latest and greatest...
from gym.benchmarks import scoring
ImportError: No module named 'gym.benchmarks'